-- Reemplazado por la migracion robusta:
-- supabase/migrations/202609150001_blackshoes_core.sql
--
-- Este archivo se conserva solo como puntero para evitar ejecutar
-- el borrador viejo por error.
--
-- Ejecutar el SQL completo desde:
-- C:\Users\Usuario\Documents\Codex\sistema-blackshoes-2026-09-08\supabase\migrations\202609150001_blackshoes_core.sql
